#+TITLE: Main Configurations

When it comes to trying to learn new things, always steal from those
that made you learn the thing in the first place. When it comes to
emacs, I will steal what I can from my Brother. If you would like to
see the original, you can find it here [[https://github.com/otfrom/otfrom-org-emacs/blob/master/org/config.org][otfrom/otfrom-org-emacs]].

* Helpers

  He created a number of helper functions that we'll need through the
  rest of this. They are incredibly useful, I recommend stealing these
  regardless if you need anything in here or not.

** load-if-exists

   This is just a nice function to load a file if it exists, but just
   print a message rather than an error if it doesn't. This is handy
   for things like loading specific local config that you don't want
   to go into github or be shared such as erc nicks, passwords, blog
   rolls, etc.

   #+BEGIN_SRC emacs-lisp
   (defun load-if-exists (file)
     (if (file-exists-p file)
	 (progn
	   (load file)
	   (message (format "Loading file: %s" file)))
       (message (format "No %s file. So not loading one." file))))
   #+END_SRC

** org-load-if-exists

   look at me adding my own helper. I want to use Babel to load other
   files into my configuration. You won't find this in the original
   repo.

   #+BEGIN_SRC emacs-lisp
   (defun org-babel-load-if-exists (file)
     (if (file-exists-p (concat user-emacs-directory file))
	 (progn
	   (org-babel-load-file (concat user-emacs-directory file))
	   (message (format "Loading file: %s" file)))
       (message (format "No %s file. So not loading one." file))))
   #+END_SRC

* Configuration

** [[file:custom/base-preferences.org][Base preferences]]

   #+BEGIN_SRC emacs-lisp
   (org-babel-load-if-exists "custom/base-preferences.org")
   #+END_SRC

** [[file:custom/org-mode-settings.org][Org mode settings]]

   #+BEGIN_SRC emacs-lisp
   (org-babel-load-if-exists "custom/org-mode-settings.org")
   #+END_SRC
